name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        target:
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-gnu

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: rust-lang/rustup-toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}

    - name: Build project
      run: cargo build --release --target ${{ matrix.target }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/${{ github.event.repository.name }}.*

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: windows-latest-x86_64-pc-windows-msvc
        path: windows

    - name: Download Linux artifact
      uses: actions/download-artifact@v4
      with:
        name: ubuntu-latest-x86_64-unknown-linux-gnu
        path: linux

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          windows/${{ github.event.repository.name }}.exe
          linux/${{ github.event.repository.name }}
